"use strict";

module.exports = {
	DEFAULT_PORT: 3000,
	DATABASE_URI: "<URI_TO_MONGODB_DATABASE",
	DATABASE_NAME: "NAME_TO_MONGODB_DATABASE",
	GTFS_VEHICLES_URI: "<URI_TO_GTFS_REALTIME_VEHICLES_RESOURCE>"
};